### ISSUE TITLE
Is the RMSprop func right?

### ISSUE THREAD

**Issue by Beronx86** [Newmu/Theano-Tutorials#4]
The function create a new shared variable named 'acc' when it is called. Will the values be accumulated in 'acc'?

**Comment by Newmu** [comment]
Yes, it's a bit weird to think about but the RMSprop function is only "called" once with the goal of creating sets of operations for theano to compile/execute many times. 

What's important is that the updates function is tuples/list of lists/ordered dict of the parameters at the current time step and then a sequence of expressions resulting in the "updated" parameters, which is what this function does.

**Comment by Beronx86** [comment]
I see. Thanks a lot.
