### ISSUE TITLE
Convnet giving error in line 44?

### ISSUE THREAD

**Issue by hitchpy** [Newmu/Theano-Tutorials#5]
Hi Newmu,

First off, thanks for putting up this tutorials, they are really nice for first time learner. I am not sure about the others but I am running the convnet example on my Mac and it gives error:
NotImplementedError: The image and the kernel must have the same type.inputs(float32), kerns(float64)

I am not sure why that is the case. Any help would be appreciated, thanks!

**Comment by Newmu** [comment]
the init_weights function uses floatX to set the dtype of the weights to keep everything consistent. if you set floatX in your theano config to be float32 it should run fine. http://deeplearning.net/software/theano/library/config.html

**Comment by hitchpy** [comment]
Indeed, problem solved. Thank you very much!

**Comment by Nidhi1211** [comment]
Traceback (most recent call last):
  File "C:\Users\Nidhi\Desktop\nidhi\M.tech_thapar\EDP Project\Theano-Tutorials-master\5_convolutional_net.py", line 77, in <module>
    noise_l1, noise_l2, noise_l3, noise_l4, noise_py_x = model(X, w, w2, w3, w4, 0.2, 0.5)
  File "C:\Users\Nidhi\Desktop\nidhi\M.tech_thapar\EDP Project\Theano-Tutorials-master\5_convolutional_net.py", line 44, in model
    l1a = rectify(conv2d(X, w, border_mode='full'))
  File "C:\Python27\lib\site-packages\theano\tensor\nnet\conv.py", line 153, in conv2d
    return op(input, filters)
  File "C:\Python27\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Python27\lib\site-packages\theano\tensor\nnet\conv.py", line 655, in make_node
    "inputs(%s), kerns(%s)" % (_inputs.dtype, _kerns.dtype))
NotImplementedError: The image and the kernel must have the same type.inputs(float32), `kerns(float64)```


[5_convolutional_net.txt](https://github.com/Newmu/Theano-Tutorials/files/916648/5_convolutional_net.txt)

**Comment by Nidhi1211** [comment]
Sir, as mentioned earlier, i am facing this error while running the code:
NotImplementedError: The image and the kernel must have the same type.inputs(float32), kerns(float64).....

Please give a suitable answer on how to resolve the error.
Thanks

**Comment by hitchpy** [comment]
How did you run your program? Seems like you ran into the same issue as I did. I think I change the running command to one specified in the link he provided:

`THEANO_FLAGS='floatX=float32,device=cuda0,lib.cnmem=1'  python <myscript>.py`

To specified the floatX to be float32 and solved the issue.

**Comment by naikzinal** [comment]
dear @hitchpy i run the code on ubantu 16.0.4 and i get the same error:

NotImplementedError: The image and the kernel must have the same type.inputs(float32), kerns(float64).....

how i can solve the issue please help me.
Thank you
